In [260]:
import numpy as np
from numpy.linalg import norm
import matplotlib.pyplot as plt
from scipy.spatial import distance

epsilon = pow(10,-9);
k=0;
q=6;
teta = 0.5
n=4;
m=2;
kMax = 15

A = np.matrix([[2,1,3,0],[-1,1,0,2]])
ct = np.matrix([1,2,1,0])
b = np.matrix([30,12])

x = np.random.uniform(1,10,n)
y=np.random.uniform(1,10,m)
s = np.random.uniform(1,10,n)

u = np.random.uniform(1,10,1)
print(u)
print(s)
print(x)
print(y)
print(A)
sk = np.zeros((n,n),float);
sk_1 = np.zeros((n,n),float);
Dk = np.zeros((n,n),float);
def diag(a,v):
    np.fill_diagonal(a,v)
pp = np.zeros((m),float)
pd = np.zeros((m),float)
vk = np.zeros((n),float)
while True:
    if(k>kMax or abs(x.dot(s))<epsilon):
        break;
    print(k)
    diag(sk,s)
    diag(Dk,x/s)
    pp = b - np.matmul(A,x)
    pd = ct - np.matmul(A.T,y) - s
#     print(pp)
#     print(pd)
    vk = u - x*s
    vk = vk[np.newaxis].T
#     print(vk)
    diag(sk_1,1/s)
#     print(sk_1)
#     print(np.matmul(A,x))
#     print(vk)
#     print(pp)
#     print(pd)
#     print(pow((A * Dk * A.T),-1))
#     print(A*sk_1*vk)
#     print(pp.A1)
#     print(A*(Dk * pd.T))
#     print(A*sk_1*vk - A*Dk * pd.T)
#     print(A * Dk * pd.T)
    print(A)
    print(pd)
    print(pp)
    dy = -pow((A * Dk * A.T),-1) * (A*sk_1*vk - A*Dk * pd.T - pp.T)
    ds = -A.T*dy + pd.T
#     print(np.matmul(sk_1,vk))
#     print(Dk * ds)
    dx = np.matmul(sk_1,vk) - Dk * ds
#     print(dy)
#     print(ds)
#     print(dx)
#     print(x/dx.A1)
    ax = -min(x/dx.A1)
    if(ax<0):
        ax=1
#     print(ax)
#     print(s/ds.A1)
    ask = -min(s/ds.A1)
    if(ask<0):
        ask=1
#     print(ask)
    amin = min(ax,ask)
#     print(amin)
    alfa = 0.999999*amin
#     print(alfa)
    x = x + alfa*dx.A1
    print("X:")
    print(x)
    y = y +alfa*dy.A1
    print("Y:")
    print(y)
    s = s+alfa*ds.A1
    print("S:")
    print(s)
    k+=1
    print(x.dot(s))
#     print()
if(abs(x.dot(s))<epsilon):
    print(x)
    print(y)
else:
    print("Fara solutie")

[4.05363675]
[4.00569287 4.16618714 4.22411612 1.97961165]
[3.77324319 5.45221702 4.32884498 6.20514049]
[2.70378966 5.98986116]
[[ 2  1  3  0]
 [-1  1  0  2]]
0
[[ 2  1  3  0]
 [-1  1  0  2]]
[[ -2.42341102 -10.85983796 -11.33548509 -13.95933397]]
[[ 4.01476167 -2.08925481]]
X:
[5.74255503 2.67302504 6.40165257 6.65969963]
Y:
[-1.55175171 -5.54534111]
S:
[-3.47188500e+00  4.16618714e-06 -3.84027446e+00 -6.02797849e-01]
-48.53603502826398
1
[[ 2  1  3  0]
 [-1  1  0  2]]
[[ 2.03004732  9.09708866  9.4955296  11.69348007]]
[[-3.3630928   1.75013074]]
X:
[ 3.47167372 12.40170929  3.23416501  1.78280414]
Y:
[1.22972945 1.40065268]
S:
[ 5.16113983e-01  1.94596178e+00 -3.84027446e-06  5.10350418e-01]
26.83487410553221
2
[[ 2  1  3  0]
 [-1  1  0  2]]
[[-0.5749202  -2.57634392 -2.68918452 -3.31165578]]
[[ 0.95244826 -0.49564386]]
X:
[4.75003249e+00 1.24017093e-05 6.83277010e+00 8.37542956e+00]
Y:
[-0.08223663 -0.1889639 ]
S:
[0.9764826  2.27556183 1.25126221 0.38353385]
16.400200051143848
3


In [220]:
pp = b - np.dot(A,x)
pd = ct - np.dot(A.T,y) - s
print(pp[0])
print(pd[0])

[[-12.26547759   4.7015811 ]]
[[-12.69815651 -14.31234496 -27.47119172 -17.14190768]]
